docker run -it --rm \
--name vllm \
--device nvidia.com/gpu=all \
--ipc=host \
--shm-size=16g \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
--network host \
-e NCCL_P2P_LEVEL=4 \
-e NCCL_IB_DISABLE=1 \
-e OMP_NUM_THREADS=8 \
-e VLLM_SKIP_P2P_CHECK=1 \
--env HF_TOKEN=${HF_TOKEN} \
-v ~/.cache/huggingface:/root/.cache/huggingface \
-v ~/.cache/vllm:/root/.cache/vllm \
lavd/vllm:jasl-dsv4-5-16-26 \
deepseek-ai/DeepSeek-V4-Flash \
  --host 0.0.0.0 \
  --port 8000 \
  --served-model-name DS4 \
  --disable-custom-all-reduce \
  --trust-remote-code \
  --tensor-parallel-size 2 \
  --kv-cache-dtype fp8_ds_mla \
  --gpu-memory-utilization 0.90 \
  --max-model-len 393216 \
  --max-num-batched-tokens 4096 \
  --distributed-executor-backend mp \
  --max-num-seqs 2 \
  --enable-prefix-caching \
  --enable-chunked-prefill \
  --tokenizer-mode deepseek_v4 \
  --reasoning-parser deepseek_v4 \
  --enable-auto-tool-choice \
  --tool-call-parser deepseek_v4 \
  --speculative-config '{"method":"mtp","num_speculative_tokens":1}'
