docker run -it --rm \
--name vllm \
--device nvidia.com/gpu=all \
--ipc=host \
--shm-size=16g \
--ulimit memlock=-1 \
--ulimit stack=67108864 \
--network host \
-e NCCL_P2P_LEVEL=4 \
-e NCCL_IB_DISABLE=1 \
-e OMP_NUM_THREADS=8 \
-e VLLM_SKIP_P2P_CHECK=1 \
-e VLLM_USE_DEEP_GEMM=0 \
-e VLLM_USE_FLASHINFER_MOE_FP16=1 \
-e VLLM_USE_FLASHINFER_SAMPLER=0 \
-v ~/.cache/huggingface:/root/.cache/huggingface \
-v ~/.cache/vllm:/root/.cache/vllm \
vllm/vllm-openai:v0.20.1 \
QuantTrio/Qwen3.6-35B-A3B-AWQ \
--host 0.0.0.0 \
--port 8000 \
--trust-remote-code \
--language-model-only \
--tensor-parallel-size 2 \
--max-model-len 262144 \
--max-num-seqs 32 \
--max-num-batched-tokens 32758 \
--max-cudagraph-capture-size 256 \
--gpu-memory-utilization 0.80 \
--kv-cache-dtype fp8 \
--enable-prefix-caching \
--enable-chunked-prefill \
--enable-auto-tool-choice \
--tool-call-parser qwen3_coder \
--reasoning-parser qwen3 \
--default-chat-template-kwargs '{"enable_thinking": false}' \
--served-model-name Qwen35
